export const categories = [
  {
    id: "e612635c-089b-43b4-9c3e-93413dd88c5e",
    createdDate: "2023-01-26T16:19:23.848Z",
    lastUpdated: "2023-03-24T22:34:59.779Z",
    availability: {
      isHidden: false,
      isAvailableNow: true,
      isUnAvailable: false,
      isTimeAvailableNow: true,
    },
    merchantId: "74d66b02-3739-46d9-896c-8a8bf7474311",
    items: [
      {
        id: "88d6193c-600f-40cc-98bd-c10fd81998a6",
        createdDate: "2023-01-26T16:18:42.283Z",
        lastUpdated: "2023-06-20T04:57:17.344Z",
        availability: {
          unavailableForStores: [],
          unavailableForStoresIds: [],
          outOfStockForStoreIds: [],
          outOfStockStores: [],
          isHidden: false,
          isAvailableNow: true,
          isUnAvailable: false,
          isTimeAvailableNow: true,
        },
        options: [
          {
            id: "cbddc99b-bb47-4f9a-8959-26da676b74d8",
            createdDate: "2023-12-29T05:22:29.706Z",
            availability: {
              isHidden: false,
              isAvailableNow: true,
              isUnAvailable: false,
            },
            items: [],
            saveOptionItems: false,
            enableMinimumSelections: false,
            enableMaximumSelections: false,
            someOptionsUnavailable: false,
            optionsCount: 0,
            menusCount: 0,
            optionSetsCount: 0,
            categoriesCount: 0,
            entityType: "MENU_OPTIONS",
            isHidden: false,
          },
          {
            id: "5f6a3739-bbe8-445a-862c-5a89a20f6b3c",
            createdDate: "2023-12-29T05:22:29.706Z",
            availability: {
              isHidden: false,
              isAvailableNow: true,
              isUnAvailable: false,
            },
            items: [],
            saveOptionItems: false,
            enableMinimumSelections: false,
            enableMaximumSelections: false,
            someOptionsUnavailable: false,
            optionsCount: 0,
            menusCount: 0,
            optionSetsCount: 0,
            categoriesCount: 0,
            entityType: "MENU_OPTIONS",
            isHidden: false,
          },
        ],
        optionSets: [
          {
            id: "cbddc99b-bb47-4f9a-8959-26da676b74d8",
            createdDate: "2023-12-29T05:22:29.706Z",
            availability: {
              isHidden: false,
              isAvailableNow: true,
              isUnAvailable: false,
            },
            items: [],
            saveOptionItems: false,
            enableMinimumSelections: false,
            enableMaximumSelections: false,
            someOptionsUnavailable: false,
            optionsCount: 0,
            menusCount: 0,
            optionSetsCount: 0,
            categoriesCount: 0,
            entityType: "MENU_OPTIONS",
            isHidden: false,
          },
          {
            id: "5f6a3739-bbe8-445a-862c-5a89a20f6b3c",
            createdDate: "2023-12-29T05:22:29.706Z",
            availability: {
              isHidden: false,
              isAvailableNow: true,
              isUnAvailable: false,
            },
            items: [],
            saveOptionItems: false,
            enableMinimumSelections: false,
            enableMaximumSelections: false,
            someOptionsUnavailable: false,
            optionsCount: 0,
            menusCount: 0,
            optionSetsCount: 0,
            categoriesCount: 0,
            entityType: "MENU_OPTIONS",
            isHidden: false,
          },
        ],
        notTaxable: false,
        merchantId: "74d66b02-3739-46d9-896c-8a8bf7474311",
        backgroundPic:
          "https://foodbit-dev-original.s3-us-west-1.amazonaws.com/images/600x/stores/energy-savings-1200x675.jpg",
        profilePic:
          "https://foodbit-dev-original.s3-us-west-1.amazonaws.com/images/300x/stores/energy-savings-1200x675.jpg",
        calories: 777,
        name: {
          en: "Sotosss",
          ar: "AR soto super",
        },
        description: {
          en: "yjjhgjhghjg",
          ar: "hjkhjghjkghjkg",
        },
        total: 143,
        price: 143,
        textToSpeech: {
          langCode: "IT",
          isEnabled: false,
        },
        foodLabels: ["GLUTEN_FREE"],
        allergies: ["EGG", "PEPPER", "SESAME", "NUT", "GLUTEN"],
        discounts: [
          {
            id: "a10bded4-8c12-496a-bf42-e52b1cb2fcdd",
            createdDate: "2023-12-29T05:22:29.742Z",
            orderTypes: ["DELIVERY", "DINE_IN", "PICKUP"],
          },
        ],
        itemsCount: 0,
        optionsCount: 2,
        menusCount: 0,
        optionSetsCount: 2,
        categoriesCount: 0,
        entityType: "MENU_ITEM",
        isHidden: false,
        taxable: true,
      },
      {
        id: "2b2b6162-fce9-462a-8ba3-55ca8ed70d3f",
        createdDate: "2023-01-26T16:39:07.828Z",
        lastUpdated: "2023-08-22T19:17:25.539Z",
        availability: {
          unavailableForStores: [],
          unavailableForStoresIds: [],
          outOfStockForStoreIds: [],
          outOfStockStores: [],
          isHidden: false,
          isAvailableNow: true,
          isUnAvailable: false,
          isTimeAvailableNow: true,
        },
        options: [
          {
            id: "cbddc99b-bb47-4f9a-8959-26da676b74d8",
            createdDate: "2023-12-29T05:22:29.706Z",
            availability: {
              isHidden: false,
              isAvailableNow: true,
              isUnAvailable: false,
            },
            items: [],
            saveOptionItems: false,
            enableMinimumSelections: false,
            enableMaximumSelections: false,
            someOptionsUnavailable: false,
            optionsCount: 0,
            menusCount: 0,
            optionSetsCount: 0,
            categoriesCount: 0,
            entityType: "MENU_OPTIONS",
            isHidden: false,
          },
          {
            id: "5f6a3739-bbe8-445a-862c-5a89a20f6b3c",
            createdDate: "2023-12-29T05:22:29.706Z",
            availability: {
              isHidden: false,
              isAvailableNow: true,
              isUnAvailable: false,
            },
            items: [],
            saveOptionItems: false,
            enableMinimumSelections: false,
            enableMaximumSelections: false,
            someOptionsUnavailable: false,
            optionsCount: 0,
            menusCount: 0,
            optionSetsCount: 0,
            categoriesCount: 0,
            entityType: "MENU_OPTIONS",
            isHidden: false,
          },
          {
            id: "88149997-ddd5-4598-83e9-9b4d1116d4ec",
            createdDate: "2023-12-29T05:22:29.706Z",
            availability: {
              isHidden: false,
              isAvailableNow: true,
              isUnAvailable: false,
            },
            items: [],
            saveOptionItems: false,
            enableMinimumSelections: false,
            enableMaximumSelections: false,
            someOptionsUnavailable: false,
            optionsCount: 0,
            menusCount: 0,
            optionSetsCount: 0,
            categoriesCount: 0,
            entityType: "MENU_OPTIONS",
            isHidden: false,
          },
          {
            id: "0c6c1690-067e-4010-a6e1-6d54d1df947b",
            createdDate: "2023-12-29T05:22:29.706Z",
            availability: {
              isHidden: false,
              isAvailableNow: true,
              isUnAvailable: false,
            },
            items: [],
            saveOptionItems: false,
            enableMinimumSelections: false,
            enableMaximumSelections: false,
            someOptionsUnavailable: false,
            optionsCount: 0,
            menusCount: 0,
            optionSetsCount: 0,
            categoriesCount: 0,
            entityType: "MENU_OPTIONS",
            isHidden: false,
          },
        ],
        optionSets: [
          {
            id: "cbddc99b-bb47-4f9a-8959-26da676b74d8",
            createdDate: "2023-12-29T05:22:29.706Z",
            availability: {
              isHidden: false,
              isAvailableNow: true,
              isUnAvailable: false,
            },
            items: [],
            saveOptionItems: false,
            enableMinimumSelections: false,
            enableMaximumSelections: false,
            someOptionsUnavailable: false,
            optionsCount: 0,
            menusCount: 0,
            optionSetsCount: 0,
            categoriesCount: 0,
            entityType: "MENU_OPTIONS",
            isHidden: false,
          },
          {
            id: "5f6a3739-bbe8-445a-862c-5a89a20f6b3c",
            createdDate: "2023-12-29T05:22:29.706Z",
            availability: {
              isHidden: false,
              isAvailableNow: true,
              isUnAvailable: false,
            },
            items: [],
            saveOptionItems: false,
            enableMinimumSelections: false,
            enableMaximumSelections: false,
            someOptionsUnavailable: false,
            optionsCount: 0,
            menusCount: 0,
            optionSetsCount: 0,
            categoriesCount: 0,
            entityType: "MENU_OPTIONS",
            isHidden: false,
          },
          {
            id: "88149997-ddd5-4598-83e9-9b4d1116d4ec",
            createdDate: "2023-12-29T05:22:29.706Z",
            availability: {
              isHidden: false,
              isAvailableNow: true,
              isUnAvailable: false,
            },
            items: [],
            saveOptionItems: false,
            enableMinimumSelections: false,
            enableMaximumSelections: false,
            someOptionsUnavailable: false,
            optionsCount: 0,
            menusCount: 0,
            optionSetsCount: 0,
            categoriesCount: 0,
            entityType: "MENU_OPTIONS",
            isHidden: false,
          },
          {
            id: "0c6c1690-067e-4010-a6e1-6d54d1df947b",
            createdDate: "2023-12-29T05:22:29.706Z",
            availability: {
              isHidden: false,
              isAvailableNow: true,
              isUnAvailable: false,
            },
            items: [],
            saveOptionItems: false,
            enableMinimumSelections: false,
            enableMaximumSelections: false,
            someOptionsUnavailable: false,
            optionsCount: 0,
            menusCount: 0,
            optionSetsCount: 0,
            categoriesCount: 0,
            entityType: "MENU_OPTIONS",
            isHidden: false,
          },
        ],
        notTaxable: false,
        merchantId: "74d66b02-3739-46d9-896c-8a8bf7474311",
        backgroundPic:
          "https://foodbit-dev-original.s3-us-west-1.amazonaws.com/images/600x/stores/beepr.jpg",
        profilePic:
          "https://foodbit-dev-original.s3-us-west-1.amazonaws.com/images/300x/stores/beepr.jpg",
        calories: 900,
        name: {
          en: "Lesah",
          ar: "AR lesah",
        },
        description: {
          id: "burger besar dengan roti lembut, patty daging sapi yang berair, tomat, selada, dan bawang",
          en: '"Try our juicy beef burger with smoked beef, sausage, and a tangy kick from hot sauce and mustard."',
          ar: "برجر كبير مع خبز طري ، شريحة لحم بقري ، طماطم ، خس ، بصل",
        },
        total: 132,
        price: 132,
        textToSpeech: {
          langCode: "EN",
          isEnabled: false,
        },
        foodLabels: ["VEGAN"],
        allergies: ["DAIRY", "LEGUMES", "SESAME", "GLUTEN", "NUT", "PEPPER"],
        discounts: [
          {
            id: "a10bded4-8c12-496a-bf42-e52b1cb2fcdd",
            createdDate: "2023-12-29T05:22:29.742Z",
            orderTypes: ["DELIVERY", "DINE_IN", "PICKUP"],
          },
        ],
        itemsCount: 0,
        optionsCount: 4,
        menusCount: 0,
        optionSetsCount: 4,
        categoriesCount: 0,
        entityType: "MENU_ITEM",
        isHidden: false,
        taxable: true,
      },
      {
        id: "be1b2b72-4b3c-4cfa-ac32-0e16faac0e9a",
        createdDate: "2023-01-26T16:41:39.397Z",
        lastUpdated: "2023-03-24T22:09:00.149Z",
        availability: {
          unavailableForStores: [],
          unavailableForStoresIds: [],
          outOfStockForStoreIds: [],
          outOfStockStores: [],
          isHidden: false,
          isAvailableNow: true,
          isUnAvailable: true,
          isTimeAvailableNow: true,
        },
        options: [
          {
            id: "cbddc99b-bb47-4f9a-8959-26da676b74d8",
            createdDate: "2023-12-29T05:22:29.706Z",
            availability: {
              isHidden: false,
              isAvailableNow: true,
              isUnAvailable: false,
            },
            items: [],
            saveOptionItems: false,
            enableMinimumSelections: false,
            enableMaximumSelections: false,
            someOptionsUnavailable: false,
            optionsCount: 0,
            menusCount: 0,
            optionSetsCount: 0,
            categoriesCount: 0,
            entityType: "MENU_OPTIONS",
            isHidden: false,
          },
          {
            id: "88149997-ddd5-4598-83e9-9b4d1116d4ec",
            createdDate: "2023-12-29T05:22:29.706Z",
            availability: {
              isHidden: false,
              isAvailableNow: true,
              isUnAvailable: false,
            },
            items: [],
            saveOptionItems: false,
            enableMinimumSelections: false,
            enableMaximumSelections: false,
            someOptionsUnavailable: false,
            optionsCount: 0,
            menusCount: 0,
            optionSetsCount: 0,
            categoriesCount: 0,
            entityType: "MENU_OPTIONS",
            isHidden: false,
          },
          {
            id: "5f6a3739-bbe8-445a-862c-5a89a20f6b3c",
            createdDate: "2023-12-29T05:22:29.706Z",
            availability: {
              isHidden: false,
              isAvailableNow: true,
              isUnAvailable: false,
            },
            items: [],
            saveOptionItems: false,
            enableMinimumSelections: false,
            enableMaximumSelections: false,
            someOptionsUnavailable: false,
            optionsCount: 0,
            menusCount: 0,
            optionSetsCount: 0,
            categoriesCount: 0,
            entityType: "MENU_OPTIONS",
            isHidden: false,
          },
        ],
        optionSets: [
          {
            id: "cbddc99b-bb47-4f9a-8959-26da676b74d8",
            createdDate: "2023-12-29T05:22:29.706Z",
            availability: {
              isHidden: false,
              isAvailableNow: true,
              isUnAvailable: false,
            },
            items: [],
            saveOptionItems: false,
            enableMinimumSelections: false,
            enableMaximumSelections: false,
            someOptionsUnavailable: false,
            optionsCount: 0,
            menusCount: 0,
            optionSetsCount: 0,
            categoriesCount: 0,
            entityType: "MENU_OPTIONS",
            isHidden: false,
          },
          {
            id: "88149997-ddd5-4598-83e9-9b4d1116d4ec",
            createdDate: "2023-12-29T05:22:29.706Z",
            availability: {
              isHidden: false,
              isAvailableNow: true,
              isUnAvailable: false,
            },
            items: [],
            saveOptionItems: false,
            enableMinimumSelections: false,
            enableMaximumSelections: false,
            someOptionsUnavailable: false,
            optionsCount: 0,
            menusCount: 0,
            optionSetsCount: 0,
            categoriesCount: 0,
            entityType: "MENU_OPTIONS",
            isHidden: false,
          },
          {
            id: "5f6a3739-bbe8-445a-862c-5a89a20f6b3c",
            createdDate: "2023-12-29T05:22:29.706Z",
            availability: {
              isHidden: false,
              isAvailableNow: true,
              isUnAvailable: false,
            },
            items: [],
            saveOptionItems: false,
            enableMinimumSelections: false,
            enableMaximumSelections: false,
            someOptionsUnavailable: false,
            optionsCount: 0,
            menusCount: 0,
            optionSetsCount: 0,
            categoriesCount: 0,
            entityType: "MENU_OPTIONS",
            isHidden: false,
          },
        ],
        notTaxable: false,
        merchantId: "74d66b02-3739-46d9-896c-8a8bf7474311",
        backgroundPic:
          "https://foodbit-dev-original.s3-us-west-1.amazonaws.com/images/600x/stores/CHW.jpg",
        profilePic:
          "https://foodbit-dev-original.s3-us-west-1.amazonaws.com/images/300x/stores/CHW.jpg",
        calories: 444,
        name: {
          en: "Bakso",
          ar: "AR bakso",
        },
        description: {
          en: "BaksoBaksoB aksoBakso Bak  oBaksoB akso",
        },
        total: 211,
        price: 211,
        itemsCount: 0,
        optionsCount: 3,
        menusCount: 0,
        optionSetsCount: 3,
        categoriesCount: 0,
        entityType: "MENU_ITEM",
        isHidden: false,
        taxable: true,
      },
      {
        id: "4dfd2687-fcb6-403a-8519-a0bf11fafdbd",
        createdDate: "2023-06-08T17:41:25.537Z",
        availability: {
          unavailableForStores: [],
          unavailableForStoresIds: [],
          outOfStockForStoreIds: [],
          outOfStockStores: [],
          isHidden: false,
          isAvailableNow: true,
          isUnAvailable: false,
          isTimeAvailableNow: true,
        },
        options: [
          {
            id: "cbddc99b-bb47-4f9a-8959-26da676b74d8",
            createdDate: "2023-12-29T05:22:29.706Z",
            availability: {
              isHidden: false,
              isAvailableNow: true,
              isUnAvailable: false,
            },
            items: [],
            saveOptionItems: false,
            enableMinimumSelections: false,
            enableMaximumSelections: false,
            someOptionsUnavailable: false,
            optionsCount: 0,
            menusCount: 0,
            optionSetsCount: 0,
            categoriesCount: 0,
            entityType: "MENU_OPTIONS",
            isHidden: false,
          },
        ],
        optionSets: [
          {
            id: "cbddc99b-bb47-4f9a-8959-26da676b74d8",
            createdDate: "2023-12-29T05:22:29.706Z",
            availability: {
              isHidden: false,
              isAvailableNow: true,
              isUnAvailable: false,
            },
            items: [],
            saveOptionItems: false,
            enableMinimumSelections: false,
            enableMaximumSelections: false,
            someOptionsUnavailable: false,
            optionsCount: 0,
            menusCount: 0,
            optionSetsCount: 0,
            categoriesCount: 0,
            entityType: "MENU_OPTIONS",
            isHidden: false,
          },
        ],
        notTaxable: false,
        merchantId: "74d66b02-3739-46d9-896c-8a8bf7474311",
        name: {
          en: "Kupat tahu",
          ar: "ar kupat tahu",
        },
        description: {
          en: "",
          ar: "",
        },
        total: 23,
        price: 23,
        allergies: ["NUT"],
        itemsCount: 0,
        optionsCount: 1,
        menusCount: 0,
        optionSetsCount: 1,
        categoriesCount: 0,
        entityType: "MENU_ITEM",
        isHidden: false,
        taxable: true,
      },
    ],
    nameEn: "Makanan Kuah",
    nameAr: "AR ",
    name: {
      en: "Makanan Kuah",
    },
    itemsCount: 5,
    optionsCount: 0,
    menusCount: 0,
    optionSetsCount: 0,
    categoriesCount: 0,
    entityType: "MENU_CATEGORY",
    areAllItemsUnAvailable: false,
    isHidden: false,
    isTemporarilyUnavailable: false,
  },
  {
    id: "a45c3f7c-fabe-421b-819b-e295d45fd918",
    createdDate: "2023-01-31T08:00:26.881Z",
    lastUpdated: "2023-03-24T21:21:28.466Z",
    availability: {
      isHidden: false,
      isAvailableNow: true,
      isUnAvailable: false,
      isTimeAvailableNow: true,
    },
    merchantId: "74d66b02-3739-46d9-896c-8a8bf7474311",
    items: [
      {
        id: "9d3d348d-7994-41ef-86ba-207459d86a22",
        createdDate: "2023-01-26T19:24:23.528Z",
        lastUpdated: "2023-04-17T20:22:11.477Z",
        availability: {
          unavailableForStores: [],
          unavailableForStoresIds: [],
          outOfStockForStoreIds: [],
          outOfStockStores: [],
          isHidden: false,
          isAvailableNow: true,
          isUnAvailable: false,
          isTimeAvailableNow: true,
        },
        options: [
          {
            id: "cbddc99b-bb47-4f9a-8959-26da676b74d8",
            createdDate: "2023-12-29T05:22:29.706Z",
            availability: {
              isHidden: false,
              isAvailableNow: true,
              isUnAvailable: false,
            },
            items: [],
            saveOptionItems: false,
            enableMinimumSelections: false,
            enableMaximumSelections: false,
            someOptionsUnavailable: false,
            optionsCount: 0,
            menusCount: 0,
            optionSetsCount: 0,
            categoriesCount: 0,
            entityType: "MENU_OPTIONS",
            isHidden: false,
          },
          {
            id: "88149997-ddd5-4598-83e9-9b4d1116d4ec",
            createdDate: "2023-12-29T05:22:29.706Z",
            availability: {
              isHidden: false,
              isAvailableNow: true,
              isUnAvailable: false,
            },
            items: [],
            saveOptionItems: false,
            enableMinimumSelections: false,
            enableMaximumSelections: false,
            someOptionsUnavailable: false,
            optionsCount: 0,
            menusCount: 0,
            optionSetsCount: 0,
            categoriesCount: 0,
            entityType: "MENU_OPTIONS",
            isHidden: false,
          },
          {
            id: "5f6a3739-bbe8-445a-862c-5a89a20f6b3c",
            createdDate: "2023-12-29T05:22:29.706Z",
            availability: {
              isHidden: false,
              isAvailableNow: true,
              isUnAvailable: false,
            },
            items: [],
            saveOptionItems: false,
            enableMinimumSelections: false,
            enableMaximumSelections: false,
            someOptionsUnavailable: false,
            optionsCount: 0,
            menusCount: 0,
            optionSetsCount: 0,
            categoriesCount: 0,
            entityType: "MENU_OPTIONS",
            isHidden: false,
          },
        ],
        optionSets: [
          {
            id: "cbddc99b-bb47-4f9a-8959-26da676b74d8",
            createdDate: "2023-12-29T05:22:29.706Z",
            availability: {
              isHidden: false,
              isAvailableNow: true,
              isUnAvailable: false,
            },
            items: [],
            saveOptionItems: false,
            enableMinimumSelections: false,
            enableMaximumSelections: false,
            someOptionsUnavailable: false,
            optionsCount: 0,
            menusCount: 0,
            optionSetsCount: 0,
            categoriesCount: 0,
            entityType: "MENU_OPTIONS",
            isHidden: false,
          },
          {
            id: "88149997-ddd5-4598-83e9-9b4d1116d4ec",
            createdDate: "2023-12-29T05:22:29.706Z",
            availability: {
              isHidden: false,
              isAvailableNow: true,
              isUnAvailable: false,
            },
            items: [],
            saveOptionItems: false,
            enableMinimumSelections: false,
            enableMaximumSelections: false,
            someOptionsUnavailable: false,
            optionsCount: 0,
            menusCount: 0,
            optionSetsCount: 0,
            categoriesCount: 0,
            entityType: "MENU_OPTIONS",
            isHidden: false,
          },
          {
            id: "5f6a3739-bbe8-445a-862c-5a89a20f6b3c",
            createdDate: "2023-12-29T05:22:29.706Z",
            availability: {
              isHidden: false,
              isAvailableNow: true,
              isUnAvailable: false,
            },
            items: [],
            saveOptionItems: false,
            enableMinimumSelections: false,
            enableMaximumSelections: false,
            someOptionsUnavailable: false,
            optionsCount: 0,
            menusCount: 0,
            optionSetsCount: 0,
            categoriesCount: 0,
            entityType: "MENU_OPTIONS",
            isHidden: false,
          },
        ],
        notTaxable: false,
        merchantId: "74d66b02-3739-46d9-896c-8a8bf7474311",
        backgroundPic:
          "https://foodbit-dev-original.s3-us-west-1.amazonaws.com/images/600x/stores/a9df14c3-6db1-46c6-945b-ed126bcc93b2.jpg",
        profilePic:
          "https://foodbit-dev-original.s3-us-west-1.amazonaws.com/images/300x/stores/a9df14c3-6db1-46c6-945b-ed126bcc93b2.jpg",
        calories: 0,
        name: {
          en: "Gudeg",
        },
        description: {
          en: "asdfasdf",
        },
        total: 212,
        price: 212,
        itemsCount: 0,
        optionsCount: 3,
        menusCount: 0,
        optionSetsCount: 3,
        categoriesCount: 0,
        entityType: "MENU_ITEM",
        isHidden: false,
        taxable: true,
      },
    ],
    nameEn: "Makanan Kering",
    name: {
      en: "Makanan Kering",
    },
    itemsCount: 2,
    optionsCount: 0,
    menusCount: 0,
    optionSetsCount: 0,
    categoriesCount: 0,
    entityType: "MENU_CATEGORY",
    areAllItemsUnAvailable: false,
    isHidden: false,
    isTemporarilyUnavailable: false,
  },
  {
    id: "d5e17b6f-e0f9-4f40-8bf8-186845ad05e2",
    createdDate: "2023-08-23T09:13:05.772Z",
    lastUpdated: "2023-08-23T09:21:42.701Z",
    availability: {
      isHidden: false,
      isAvailableNow: true,
      isUnAvailable: false,
      isTimeAvailableNow: true,
    },
    merchantId: "74d66b02-3739-46d9-896c-8a8bf7474311",
    items: [
      {
        id: "d8191805-b3e3-4163-b1f9-fb3151685c33",
        createdDate: "2023-08-23T09:21:28.823Z",
        lastUpdated: "2023-08-23T10:02:40.566Z",
        availability: {
          isHidden: false,
          isAvailableNow: true,
          isUnAvailable: false,
          isTimeAvailableNow: true,
        },
        merchantId: "74d66b02-3739-46d9-896c-8a8bf7474311",
        name: {
          en: "coba thai spicy",
        },
        description: {
          en: "",
        },
        total: 25,
        price: 25,
        itemsCount: 0,
        optionsCount: 0,
        menusCount: 0,
        optionSetsCount: 0,
        categoriesCount: 0,
        entityType: "MENU_ITEM",
        isHidden: false,
      },
      {
        id: "7cf63e96-1782-4d03-83aa-a6fc7e15c29b",
        createdDate: "2023-08-23T09:21:41.286Z",
        lastUpdated: "2023-08-23T10:02:32.814Z",
        availability: {
          isHidden: false,
          isAvailableNow: true,
          isUnAvailable: false,
          isTimeAvailableNow: true,
        },
        merchantId: "74d66b02-3739-46d9-896c-8a8bf7474311",
        name: {
          en: "spicy thai spring roll",
        },
        description: {
          en: "",
        },
        total: 45,
        price: 45,
        itemsCount: 0,
        optionsCount: 0,
        menusCount: 0,
        optionSetsCount: 0,
        categoriesCount: 0,
        entityType: "MENU_ITEM",
        isHidden: false,
      },
    ],
    nameEn: "Makanan kuah thailand",
    name: {
      en: "Makanan thai",
    },
    itemsCount: 2,
    optionsCount: 0,
    menusCount: 0,
    optionSetsCount: 0,
    categoriesCount: 0,
    entityType: "MENU_CATEGORY",
    areAllItemsUnAvailable: false,
    isHidden: false,
    isTemporarilyUnavailable: false,
  },
];

export const items = [
  {
    id: "4dfd2687-fcb6-403a-8519-a0bf11fafdbd",
    createdDate: "2023-06-08T17:41:25.537Z",
    availability: {
      unavailableForStores: [],
      unavailableForStoresIds: [],
      outOfStockForStoreIds: [],
      outOfStockStores: [],
      isHidden: false,
      isAvailableNow: true,
      isUnAvailable: false,
    },
    options: [
      {
        id: "cbddc99b-bb47-4f9a-8959-26da676b74d8",
        createdDate: "2023-12-29T10:17:53.424Z",
        availability: {
          isHidden: false,
          isAvailableNow: true,
          isUnAvailable: false,
        },
        items: [],
        saveOptionItems: false,
        enableMinimumSelections: false,
        enableMaximumSelections: false,
        someOptionsUnavailable: false,
        optionsCount: 0,
        menusCount: 0,
        optionSetsCount: 0,
        categoriesCount: 0,
        entityType: "MENU_OPTIONS",
        isHidden: false,
      },
    ],
    optionSets: [
      {
        id: "cbddc99b-bb47-4f9a-8959-26da676b74d8",
        createdDate: "2023-12-29T10:17:53.424Z",
        availability: {
          isHidden: false,
          isAvailableNow: true,
          isUnAvailable: false,
        },
        items: [],
        saveOptionItems: false,
        enableMinimumSelections: false,
        enableMaximumSelections: false,
        someOptionsUnavailable: false,
        optionsCount: 0,
        menusCount: 0,
        optionSetsCount: 0,
        categoriesCount: 0,
        entityType: "MENU_OPTIONS",
        isHidden: false,
      },
    ],
    categories: [
      {
        id: "e612635c-089b-43b4-9c3e-93413dd88c5e",
        createdDate: "2023-12-29T10:17:53.430Z",
        availability: {
          isHidden: false,
          isAvailableNow: true,
          isUnAvailable: false,
        },
        itemsCount: 0,
        optionsCount: 0,
        menusCount: 0,
        optionSetsCount: 0,
        categoriesCount: 0,
        entityType: "MENU_CATEGORY",
        isHidden: false,
      },
    ],
    notTaxable: false,
    merchantId: "74d66b02-3739-46d9-896c-8a8bf7474311",
    name: {
      en: "Kupat tahu",
      ar: "ar kupat tahu",
    },
    description: {
      en: "",
      ar: "",
    },
    total: 23.0,
    price: 23.0,
    allergies: ["NUT"],
    itemsCount: 0,
    optionsCount: 1,
    menusCount: 0,
    optionSetsCount: 1,
    categoriesCount: 1,
    entityType: "MENU_ITEM",
    isHidden: false,
    taxable: true,
  },
  {
    id: "7c9a200c-df72-4179-a92b-f8e4795b6105",
    createdDate: "2023-06-08T09:56:15.316Z",
    lastUpdated: "2023-06-08T17:23:24.209Z",
    availability: {
      unavailableForStores: [],
      unavailableForStoresIds: [],
      outOfStockForStoreIds: [],
      outOfStockStores: [],
      isHidden: false,
      isAvailableNow: true,
      isUnAvailable: false,
    },
    categories: [],
    notTaxable: false,
    merchantId: "74d66b02-3739-46d9-896c-8a8bf7474311",
    name: {
      en: "Tahu Petis",
      ar: "Tahu Petis",
      fr: "",
    },
    description: {
      en: "tahu yang lembut dengan petis udang yang lezat",
      ar: "",
      fr: "",
    },
    total: 22.0,
    price: 22.0,
    textToSpeech: {
      langCode: "EN",
      isEnabled: false,
    },
    itemsCount: 0,
    optionsCount: 0,
    menusCount: 0,
    optionSetsCount: 0,
    categoriesCount: 0,
    entityType: "MENU_ITEM",
    isHidden: false,
    taxable: true,
  },
  {
    id: "9f49548a-de01-43cc-9081-3edcbd00a287",
    createdDate: "2023-08-23T10:11:28.617Z",
    lastUpdated: "2023-09-22T11:36:30.304Z",
    availability: {
      unavailableForStores: [],
      unavailableForStoresIds: [],
      outOfStockForStoreIds: [],
      outOfStockStores: [],
      isHidden: false,
      isAvailableNow: true,
      isUnAvailable: false,
    },
    options: [
      {
        id: "0c6c1690-067e-4010-a6e1-6d54d1df947b",
        createdDate: "2023-12-29T10:17:53.424Z",
        availability: {
          isHidden: false,
          isAvailableNow: true,
          isUnAvailable: false,
        },
        items: [],
        saveOptionItems: false,
        enableMinimumSelections: false,
        enableMaximumSelections: false,
        someOptionsUnavailable: false,
        optionsCount: 0,
        menusCount: 0,
        optionSetsCount: 0,
        categoriesCount: 0,
        entityType: "MENU_OPTIONS",
        isHidden: false,
      },
      {
        id: "8e9035ff-339e-41f0-a43b-9c9efaa4681a",
        createdDate: "2023-12-29T10:17:53.424Z",
        availability: {
          isHidden: false,
          isAvailableNow: true,
          isUnAvailable: false,
        },
        items: [],
        saveOptionItems: false,
        enableMinimumSelections: false,
        enableMaximumSelections: false,
        someOptionsUnavailable: false,
        optionsCount: 0,
        menusCount: 0,
        optionSetsCount: 0,
        categoriesCount: 0,
        entityType: "MENU_OPTIONS",
        isHidden: false,
      },
    ],
    optionSets: [
      {
        id: "0c6c1690-067e-4010-a6e1-6d54d1df947b",
        createdDate: "2023-12-29T10:17:53.424Z",
        availability: {
          isHidden: false,
          isAvailableNow: true,
          isUnAvailable: false,
        },
        items: [],
        saveOptionItems: false,
        enableMinimumSelections: false,
        enableMaximumSelections: false,
        someOptionsUnavailable: false,
        optionsCount: 0,
        menusCount: 0,
        optionSetsCount: 0,
        categoriesCount: 0,
        entityType: "MENU_OPTIONS",
        isHidden: false,
      },
      {
        id: "8e9035ff-339e-41f0-a43b-9c9efaa4681a",
        createdDate: "2023-12-29T10:17:53.424Z",
        availability: {
          isHidden: false,
          isAvailableNow: true,
          isUnAvailable: false,
        },
        items: [],
        saveOptionItems: false,
        enableMinimumSelections: false,
        enableMaximumSelections: false,
        someOptionsUnavailable: false,
        optionsCount: 0,
        menusCount: 0,
        optionSetsCount: 0,
        categoriesCount: 0,
        entityType: "MENU_OPTIONS",
        isHidden: false,
      },
    ],
    categories: [
      {
        id: "5931475d-da2e-453e-8fd1-b70ca6e46675",
        createdDate: "2023-12-29T10:17:53.430Z",
        availability: {
          isHidden: false,
          isAvailableNow: true,
          isUnAvailable: false,
        },
        itemsCount: 0,
        optionsCount: 0,
        menusCount: 0,
        optionSetsCount: 0,
        categoriesCount: 0,
        entityType: "MENU_CATEGORY",
        isHidden: false,
      },
      {
        id: "fd2379b7-7c73-405f-b605-30b9de8d9f9d",
        createdDate: "2023-12-29T10:17:53.430Z",
        availability: {
          isHidden: false,
          isAvailableNow: true,
          isUnAvailable: false,
        },
        itemsCount: 0,
        optionsCount: 0,
        menusCount: 0,
        optionSetsCount: 0,
        categoriesCount: 0,
        entityType: "MENU_CATEGORY",
        isHidden: false,
      },
    ],
    notTaxable: false,
    merchantId: "74d66b02-3739-46d9-896c-8a8bf7474311",
    name: {
      en: "item baru coba",
    },
    description: {
      en: "",
    },
    total: 36.0,
    price: 36.0,
    textToSpeech: {
      langCode: "EN",
      isEnabled: null,
    },
    foodLabels: ["GLUTEN_FREE"],
    allergies: ["GARLIC", "ONION"],
    nutrition: {
      fat: 30.0,
      carbs: 50.0,
      sugar: 8.0,
      protein: 150.0,
      fiber: 40.0,
    },
    itemsCount: 0,
    optionsCount: 2,
    menusCount: 0,
    optionSetsCount: 2,
    categoriesCount: 2,
    entityType: "MENU_ITEM",
    isHidden: false,
    taxable: true,
  },
  {
    id: "2b2b6162-fce9-462a-8ba3-55ca8ed70d3f",
    createdDate: "2023-01-26T16:39:07.828Z",
    lastUpdated: "2023-08-22T19:17:25.539Z",
    availability: {
      unavailableForStores: [],
      unavailableForStoresIds: [],
      outOfStockForStoreIds: [],
      outOfStockStores: [],
      isHidden: false,
      isAvailableNow: true,
      isUnAvailable: false,
    },
    options: [
      {
        id: "cbddc99b-bb47-4f9a-8959-26da676b74d8",
        createdDate: "2023-12-29T10:17:53.424Z",
        availability: {
          isHidden: false,
          isAvailableNow: true,
          isUnAvailable: false,
        },
        items: [],
        saveOptionItems: false,
        enableMinimumSelections: false,
        enableMaximumSelections: false,
        someOptionsUnavailable: false,
        optionsCount: 0,
        menusCount: 0,
        optionSetsCount: 0,
        categoriesCount: 0,
        entityType: "MENU_OPTIONS",
        isHidden: false,
      },
      {
        id: "5f6a3739-bbe8-445a-862c-5a89a20f6b3c",
        createdDate: "2023-12-29T10:17:53.424Z",
        availability: {
          isHidden: false,
          isAvailableNow: true,
          isUnAvailable: false,
        },
        items: [],
        saveOptionItems: false,
        enableMinimumSelections: false,
        enableMaximumSelections: false,
        someOptionsUnavailable: false,
        optionsCount: 0,
        menusCount: 0,
        optionSetsCount: 0,
        categoriesCount: 0,
        entityType: "MENU_OPTIONS",
        isHidden: false,
      },
      {
        id: "88149997-ddd5-4598-83e9-9b4d1116d4ec",
        createdDate: "2023-12-29T10:17:53.424Z",
        availability: {
          isHidden: false,
          isAvailableNow: true,
          isUnAvailable: false,
        },
        items: [],
        saveOptionItems: false,
        enableMinimumSelections: false,
        enableMaximumSelections: false,
        someOptionsUnavailable: false,
        optionsCount: 0,
        menusCount: 0,
        optionSetsCount: 0,
        categoriesCount: 0,
        entityType: "MENU_OPTIONS",
        isHidden: false,
      },
      {
        id: "0c6c1690-067e-4010-a6e1-6d54d1df947b",
        createdDate: "2023-12-29T10:17:53.424Z",
        availability: {
          isHidden: false,
          isAvailableNow: true,
          isUnAvailable: false,
        },
        items: [],
        saveOptionItems: false,
        enableMinimumSelections: false,
        enableMaximumSelections: false,
        someOptionsUnavailable: false,
        optionsCount: 0,
        menusCount: 0,
        optionSetsCount: 0,
        categoriesCount: 0,
        entityType: "MENU_OPTIONS",
        isHidden: false,
      },
    ],
    optionSets: [
      {
        id: "cbddc99b-bb47-4f9a-8959-26da676b74d8",
        createdDate: "2023-12-29T10:17:53.424Z",
        availability: {
          isHidden: false,
          isAvailableNow: true,
          isUnAvailable: false,
        },
        items: [],
        saveOptionItems: false,
        enableMinimumSelections: false,
        enableMaximumSelections: false,
        someOptionsUnavailable: false,
        optionsCount: 0,
        menusCount: 0,
        optionSetsCount: 0,
        categoriesCount: 0,
        entityType: "MENU_OPTIONS",
        isHidden: false,
      },
      {
        id: "5f6a3739-bbe8-445a-862c-5a89a20f6b3c",
        createdDate: "2023-12-29T10:17:53.424Z",
        availability: {
          isHidden: false,
          isAvailableNow: true,
          isUnAvailable: false,
        },
        items: [],
        saveOptionItems: false,
        enableMinimumSelections: false,
        enableMaximumSelections: false,
        someOptionsUnavailable: false,
        optionsCount: 0,
        menusCount: 0,
        optionSetsCount: 0,
        categoriesCount: 0,
        entityType: "MENU_OPTIONS",
        isHidden: false,
      },
      {
        id: "88149997-ddd5-4598-83e9-9b4d1116d4ec",
        createdDate: "2023-12-29T10:17:53.424Z",
        availability: {
          isHidden: false,
          isAvailableNow: true,
          isUnAvailable: false,
        },
        items: [],
        saveOptionItems: false,
        enableMinimumSelections: false,
        enableMaximumSelections: false,
        someOptionsUnavailable: false,
        optionsCount: 0,
        menusCount: 0,
        optionSetsCount: 0,
        categoriesCount: 0,
        entityType: "MENU_OPTIONS",
        isHidden: false,
      },
      {
        id: "0c6c1690-067e-4010-a6e1-6d54d1df947b",
        createdDate: "2023-12-29T10:17:53.424Z",
        availability: {
          isHidden: false,
          isAvailableNow: true,
          isUnAvailable: false,
        },
        items: [],
        saveOptionItems: false,
        enableMinimumSelections: false,
        enableMaximumSelections: false,
        someOptionsUnavailable: false,
        optionsCount: 0,
        menusCount: 0,
        optionSetsCount: 0,
        categoriesCount: 0,
        entityType: "MENU_OPTIONS",
        isHidden: false,
      },
    ],
    categories: [
      {
        id: "e612635c-089b-43b4-9c3e-93413dd88c5e",
        createdDate: "2023-12-29T10:17:53.430Z",
        availability: {
          isHidden: false,
          isAvailableNow: true,
          isUnAvailable: false,
        },
        itemsCount: 0,
        optionsCount: 0,
        menusCount: 0,
        optionSetsCount: 0,
        categoriesCount: 0,
        entityType: "MENU_CATEGORY",
        isHidden: false,
      },
    ],
    notTaxable: false,
    merchantId: "74d66b02-3739-46d9-896c-8a8bf7474311",
    backgroundPic:
      "https://foodbit-dev-original.s3-us-west-1.amazonaws.com/images/600x/stores/beepr.jpg",
    profilePic:
      "https://foodbit-dev-original.s3-us-west-1.amazonaws.com/images/300x/stores/beepr.jpg",
    calories: 900,
    name: {
      en: "Lesah",
      ar: "AR lesah",
    },
    description: {
      id: "burger besar dengan roti lembut, patty daging sapi yang berair, tomat, selada, dan bawang",
      en: '"Try our juicy beef burger with smoked beef, sausage, and a tangy kick from hot sauce and mustard."',
      ar: "برجر كبير مع خبز طري ، شريحة لحم بقري ، طماطم ، خس ، بصل",
    },
    total: 132.0,
    price: 132.0,
    textToSpeech: {
      langCode: "EN",
      isEnabled: false,
    },
    foodLabels: ["VEGAN"],
    allergies: ["DAIRY", "LEGUMES", "SESAME", "GLUTEN", "NUT", "PEPPER"],
    itemsCount: 0,
    optionsCount: 4,
    menusCount: 0,
    optionSetsCount: 4,
    categoriesCount: 1,
    entityType: "MENU_ITEM",
    isHidden: false,
    taxable: true,
  },
  {
    id: "23c9ec61-f3aa-4dd7-83bc-6f35688130d7",
    createdDate: "2023-06-08T17:43:02.127Z",
    lastUpdated: "2023-06-11T17:34:38.036Z",
    availability: {
      unavailableForStores: [],
      unavailableForStoresIds: [],
      outOfStockForStoreIds: [],
      outOfStockStores: [],
      isHidden: false,
      isAvailableNow: true,
      isUnAvailable: false,
    },
    categories: [
      {
        id: "cf95ef05-f47d-4eb6-95fa-4e0449cd1e5e",
        createdDate: "2023-12-29T10:17:53.430Z",
        availability: {
          isHidden: false,
          isAvailableNow: true,
          isUnAvailable: false,
        },
        itemsCount: 0,
        optionsCount: 0,
        menusCount: 0,
        optionSetsCount: 0,
        categoriesCount: 0,
        entityType: "MENU_CATEGORY",
        isHidden: false,
      },
    ],
    notTaxable: false,
    merchantId: "74d66b02-3739-46d9-896c-8a8bf7474311",
    name: {
      en: "meat lover pizza",
      ar: "ar memat lover pizza",
    },
    description: {
      en: '"Savor the flavor of our juicy burger topped with savory sausage, caramelized onions, and fresh tomatoes, all nestled in soft buns."',
      ar: "",
    },
    total: 77.0,
    price: 77.0,
    textToSpeech: {
      langCode: "EN",
      isEnabled: false,
    },
    itemsCount: 0,
    optionsCount: 0,
    menusCount: 0,
    optionSetsCount: 0,
    categoriesCount: 1,
    entityType: "MENU_ITEM",
    isHidden: false,
    taxable: true,
  },
  {
    id: "71b18335-ca4b-48f3-bde8-448c576ded44",
    createdDate: "2023-05-31T00:00:32.138Z",
    availability: {
      isHidden: false,
      isAvailableNow: true,
      isUnAvailable: false,
    },
    categories: [
      {
        id: "cf95ef05-f47d-4eb6-95fa-4e0449cd1e5e",
        createdDate: "2023-12-29T10:17:53.430Z",
        availability: {
          isHidden: false,
          isAvailableNow: true,
          isUnAvailable: false,
        },
        itemsCount: 0,
        optionsCount: 0,
        menusCount: 0,
        optionSetsCount: 0,
        categoriesCount: 0,
        entityType: "MENU_CATEGORY",
        isHidden: false,
      },
    ],
    notTaxable: false,
    merchantId: "74d66b02-3739-46d9-896c-8a8bf7474311",
    name: {
      en: "Vegie Pizza",
      ar: "AR Vegie Pizza",
    },
    description: {},
    total: 68.0,
    price: 68.0,
    itemsCount: 0,
    optionsCount: 0,
    menusCount: 0,
    optionSetsCount: 0,
    categoriesCount: 1,
    entityType: "MENU_ITEM",
    isHidden: false,
    taxable: true,
  },
  {
    id: "124fdd54-ed60-4309-9b5c-04ce2c455391",
    createdDate: "2023-06-04T07:28:47.099Z",
    availability: {
      isHidden: false,
      isAvailableNow: true,
      isUnAvailable: false,
    },
    categories: [],
    notTaxable: false,
    merchantId: "74d66b02-3739-46d9-896c-8a8bf7474311",
    name: {
      en: "tempe",
      ar: "ar asdgfd",
    },
    description: {
      en: "",
      ar: "",
    },
    total: 45.0,
    price: 45.0,
    itemsCount: 0,
    optionsCount: 0,
    menusCount: 0,
    optionSetsCount: 0,
    categoriesCount: 0,
    entityType: "MENU_ITEM",
    isHidden: false,
    taxable: true,
  },
  {
    id: "6f17c814-3974-42c4-822b-69d8122d4de1",
    createdDate: "2023-06-21T17:30:14.223Z",
    lastUpdated: "2023-06-27T18:27:36.514Z",
    availability: {
      unavailableForStores: [],
      unavailableForStoresIds: [],
      outOfStockForStoreIds: [],
      outOfStockStores: [],
      isHidden: false,
      isAvailableNow: true,
      isUnAvailable: false,
    },
    options: [
      {
        id: "cbddc99b-bb47-4f9a-8959-26da676b74d8",
        createdDate: "2023-12-29T10:17:53.424Z",
        availability: {
          isHidden: false,
          isAvailableNow: true,
          isUnAvailable: false,
        },
        items: [],
        saveOptionItems: false,
        enableMinimumSelections: false,
        enableMaximumSelections: false,
        someOptionsUnavailable: false,
        optionsCount: 0,
        menusCount: 0,
        optionSetsCount: 0,
        categoriesCount: 0,
        entityType: "MENU_OPTIONS",
        isHidden: false,
      },
      {
        id: "5f6a3739-bbe8-445a-862c-5a89a20f6b3c",
        createdDate: "2023-12-29T10:17:53.424Z",
        availability: {
          isHidden: false,
          isAvailableNow: true,
          isUnAvailable: false,
        },
        items: [],
        saveOptionItems: false,
        enableMinimumSelections: false,
        enableMaximumSelections: false,
        someOptionsUnavailable: false,
        optionsCount: 0,
        menusCount: 0,
        optionSetsCount: 0,
        categoriesCount: 0,
        entityType: "MENU_OPTIONS",
        isHidden: false,
      },
    ],
    optionSets: [
      {
        id: "cbddc99b-bb47-4f9a-8959-26da676b74d8",
        createdDate: "2023-12-29T10:17:53.424Z",
        availability: {
          isHidden: false,
          isAvailableNow: true,
          isUnAvailable: false,
        },
        items: [],
        saveOptionItems: false,
        enableMinimumSelections: false,
        enableMaximumSelections: false,
        someOptionsUnavailable: false,
        optionsCount: 0,
        menusCount: 0,
        optionSetsCount: 0,
        categoriesCount: 0,
        entityType: "MENU_OPTIONS",
        isHidden: false,
      },
      {
        id: "5f6a3739-bbe8-445a-862c-5a89a20f6b3c",
        createdDate: "2023-12-29T10:17:53.424Z",
        availability: {
          isHidden: false,
          isAvailableNow: true,
          isUnAvailable: false,
        },
        items: [],
        saveOptionItems: false,
        enableMinimumSelections: false,
        enableMaximumSelections: false,
        someOptionsUnavailable: false,
        optionsCount: 0,
        menusCount: 0,
        optionSetsCount: 0,
        categoriesCount: 0,
        entityType: "MENU_OPTIONS",
        isHidden: false,
      },
    ],
    categories: [
      {
        id: "bae09f71-5712-4e4a-ba1e-adc599ee0541",
        createdDate: "2023-12-29T10:17:53.430Z",
        availability: {
          isHidden: false,
          isAvailableNow: true,
          isUnAvailable: false,
        },
        itemsCount: 0,
        optionsCount: 0,
        menusCount: 0,
        optionSetsCount: 0,
        categoriesCount: 0,
        entityType: "MENU_CATEGORY",
        isHidden: false,
      },
    ],
    notTaxable: false,
    merchantId: "74d66b02-3739-46d9-896c-8a8bf7474311",
    name: {
      en: "Burger with Fries",
      ar: "AR Burger with Fries",
    },
    description: {
      en: "Our classic burger and fries combo is sure to satisfy any craving! Perfectly seasoned fries accompany a juicy burger patty. super duper wow!!!",
      ar: "",
    },
    total: 34.0,
    price: 34.0,
    textToSpeech: {
      langCode: "EN",
      isEnabled: false,
    },
    foodLabels: ["GLUTEN_FREE"],
    allergies: ["PEPPER", "EGG"],
    itemsCount: 0,
    optionsCount: 2,
    menusCount: 0,
    optionSetsCount: 2,
    categoriesCount: 1,
    entityType: "MENU_ITEM",
    isHidden: false,
    taxable: true,
  },
  {
    id: "8ebba200-43e4-4cc9-a8cf-150bc6ee979d",
    createdDate: "2023-05-31T00:01:30.920Z",
    availability: {
      unavailableForStores: [],
      unavailableForStoresIds: [],
      outOfStockForStoreIds: [],
      outOfStockStores: [],
      isHidden: false,
      isAvailableNow: true,
      isUnAvailable: false,
    },
    categories: [
      {
        id: "bae09f71-5712-4e4a-ba1e-adc599ee0541",
        createdDate: "2023-12-29T10:17:53.430Z",
        availability: {
          isHidden: false,
          isAvailableNow: true,
          isUnAvailable: false,
        },
        itemsCount: 0,
        optionsCount: 0,
        menusCount: 0,
        optionSetsCount: 0,
        categoriesCount: 0,
        entityType: "MENU_CATEGORY",
        isHidden: false,
      },
    ],
    notTaxable: false,
    merchantId: "74d66b02-3739-46d9-896c-8a8bf7474311",
    name: {
      en: "Beef Burger",
      ar: "AR Burger",
    },
    description: {},
    total: 76.0,
    price: 76.0,
    itemsCount: 0,
    optionsCount: 0,
    menusCount: 0,
    optionSetsCount: 0,
    categoriesCount: 1,
    entityType: "MENU_ITEM",
    isHidden: false,
    taxable: true,
  },
  {
    id: "9d3d348d-7994-41ef-86ba-207459d86a22",
    createdDate: "2023-01-26T19:24:23.528Z",
    lastUpdated: "2023-04-17T20:22:11.477Z",
    availability: {
      unavailableForStores: [],
      unavailableForStoresIds: [],
      outOfStockForStoreIds: [],
      outOfStockStores: [],
      isHidden: false,
      isAvailableNow: true,
      isUnAvailable: false,
    },
    options: [
      {
        id: "cbddc99b-bb47-4f9a-8959-26da676b74d8",
        createdDate: "2023-12-29T10:17:53.424Z",
        availability: {
          isHidden: false,
          isAvailableNow: true,
          isUnAvailable: false,
        },
        items: [],
        saveOptionItems: false,
        enableMinimumSelections: false,
        enableMaximumSelections: false,
        someOptionsUnavailable: false,
        optionsCount: 0,
        menusCount: 0,
        optionSetsCount: 0,
        categoriesCount: 0,
        entityType: "MENU_OPTIONS",
        isHidden: false,
      },
      {
        id: "88149997-ddd5-4598-83e9-9b4d1116d4ec",
        createdDate: "2023-12-29T10:17:53.424Z",
        availability: {
          isHidden: false,
          isAvailableNow: true,
          isUnAvailable: false,
        },
        items: [],
        saveOptionItems: false,
        enableMinimumSelections: false,
        enableMaximumSelections: false,
        someOptionsUnavailable: false,
        optionsCount: 0,
        menusCount: 0,
        optionSetsCount: 0,
        categoriesCount: 0,
        entityType: "MENU_OPTIONS",
        isHidden: false,
      },
      {
        id: "5f6a3739-bbe8-445a-862c-5a89a20f6b3c",
        createdDate: "2023-12-29T10:17:53.424Z",
        availability: {
          isHidden: false,
          isAvailableNow: true,
          isUnAvailable: false,
        },
        items: [],
        saveOptionItems: false,
        enableMinimumSelections: false,
        enableMaximumSelections: false,
        someOptionsUnavailable: false,
        optionsCount: 0,
        menusCount: 0,
        optionSetsCount: 0,
        categoriesCount: 0,
        entityType: "MENU_OPTIONS",
        isHidden: false,
      },
    ],
    optionSets: [
      {
        id: "cbddc99b-bb47-4f9a-8959-26da676b74d8",
        createdDate: "2023-12-29T10:17:53.424Z",
        availability: {
          isHidden: false,
          isAvailableNow: true,
          isUnAvailable: false,
        },
        items: [],
        saveOptionItems: false,
        enableMinimumSelections: false,
        enableMaximumSelections: false,
        someOptionsUnavailable: false,
        optionsCount: 0,
        menusCount: 0,
        optionSetsCount: 0,
        categoriesCount: 0,
        entityType: "MENU_OPTIONS",
        isHidden: false,
      },
      {
        id: "88149997-ddd5-4598-83e9-9b4d1116d4ec",
        createdDate: "2023-12-29T10:17:53.424Z",
        availability: {
          isHidden: false,
          isAvailableNow: true,
          isUnAvailable: false,
        },
        items: [],
        saveOptionItems: false,
        enableMinimumSelections: false,
        enableMaximumSelections: false,
        someOptionsUnavailable: false,
        optionsCount: 0,
        menusCount: 0,
        optionSetsCount: 0,
        categoriesCount: 0,
        entityType: "MENU_OPTIONS",
        isHidden: false,
      },
      {
        id: "5f6a3739-bbe8-445a-862c-5a89a20f6b3c",
        createdDate: "2023-12-29T10:17:53.424Z",
        availability: {
          isHidden: false,
          isAvailableNow: true,
          isUnAvailable: false,
        },
        items: [],
        saveOptionItems: false,
        enableMinimumSelections: false,
        enableMaximumSelections: false,
        someOptionsUnavailable: false,
        optionsCount: 0,
        menusCount: 0,
        optionSetsCount: 0,
        categoriesCount: 0,
        entityType: "MENU_OPTIONS",
        isHidden: false,
      },
    ],
    categories: [
      {
        id: "a45c3f7c-fabe-421b-819b-e295d45fd918",
        createdDate: "2023-12-29T10:17:53.430Z",
        availability: {
          isHidden: false,
          isAvailableNow: true,
          isUnAvailable: false,
        },
        itemsCount: 0,
        optionsCount: 0,
        menusCount: 0,
        optionSetsCount: 0,
        categoriesCount: 0,
        entityType: "MENU_CATEGORY",
        isHidden: false,
      },
      {
        id: "e612635c-089b-43b4-9c3e-93413dd88c5e",
        createdDate: "2023-12-29T10:17:53.430Z",
        availability: {
          isHidden: false,
          isAvailableNow: true,
          isUnAvailable: false,
        },
        itemsCount: 0,
        optionsCount: 0,
        menusCount: 0,
        optionSetsCount: 0,
        categoriesCount: 0,
        entityType: "MENU_CATEGORY",
        isHidden: false,
      },
    ],
    notTaxable: false,
    merchantId: "74d66b02-3739-46d9-896c-8a8bf7474311",
    backgroundPic:
      "https://foodbit-dev-original.s3-us-west-1.amazonaws.com/images/600x/stores/a9df14c3-6db1-46c6-945b-ed126bcc93b2.jpg",
    profilePic:
      "https://foodbit-dev-original.s3-us-west-1.amazonaws.com/images/300x/stores/a9df14c3-6db1-46c6-945b-ed126bcc93b2.jpg",
    calories: 0,
    name: {
      en: "Gudeg",
    },
    description: {
      en: "asdfasdf",
    },
    total: 212.0,
    price: 212.0,
    itemsCount: 0,
    optionsCount: 3,
    menusCount: 0,
    optionSetsCount: 3,
    categoriesCount: 2,
    entityType: "MENU_ITEM",
    isHidden: false,
    taxable: true,
  },
  {
    id: "17bfe6c0-eb08-4f84-9e03-feb19cfe18ee",
    createdDate: "2023-05-30T23:59:41.820Z",
    lastUpdated: "2023-05-30T23:59:53.409Z",
    availability: {
      unavailableForStores: [],
      unavailableForStoresIds: [],
      outOfStockForStoreIds: [],
      outOfStockStores: [],
      isHidden: false,
      isAvailableNow: true,
      isUnAvailable: false,
    },
    categories: [
      {
        id: "cf95ef05-f47d-4eb6-95fa-4e0449cd1e5e",
        createdDate: "2023-12-29T10:17:53.430Z",
        availability: {
          isHidden: false,
          isAvailableNow: true,
          isUnAvailable: false,
        },
        itemsCount: 0,
        optionsCount: 0,
        menusCount: 0,
        optionSetsCount: 0,
        categoriesCount: 0,
        entityType: "MENU_CATEGORY",
        isHidden: false,
      },
    ],
    notTaxable: false,
    merchantId: "74d66b02-3739-46d9-896c-8a8bf7474311",
    name: {
      en: "Carbonara Pizza",
      ar: "AR Carbonara pizza",
    },
    description: {},
    total: 78.0,
    price: 78.0,
    textToSpeech: {
      langCode: "IT",
      isEnabled: false,
    },
    itemsCount: 0,
    optionsCount: 0,
    menusCount: 0,
    optionSetsCount: 0,
    categoriesCount: 1,
    entityType: "MENU_ITEM",
    isHidden: false,
    taxable: true,
  },
  {
    id: "88d6193c-600f-40cc-98bd-c10fd81998a6",
    createdDate: "2023-01-26T16:18:42.283Z",
    lastUpdated: "2023-06-20T04:57:17.344Z",
    availability: {
      unavailableForStores: [],
      unavailableForStoresIds: [],
      outOfStockForStoreIds: [],
      outOfStockStores: [],
      isHidden: false,
      isAvailableNow: true,
      isUnAvailable: false,
    },
    options: [
      {
        id: "cbddc99b-bb47-4f9a-8959-26da676b74d8",
        createdDate: "2023-12-29T10:17:53.424Z",
        availability: {
          isHidden: false,
          isAvailableNow: true,
          isUnAvailable: false,
        },
        items: [],
        saveOptionItems: false,
        enableMinimumSelections: false,
        enableMaximumSelections: false,
        someOptionsUnavailable: false,
        optionsCount: 0,
        menusCount: 0,
        optionSetsCount: 0,
        categoriesCount: 0,
        entityType: "MENU_OPTIONS",
        isHidden: false,
      },
      {
        id: "5f6a3739-bbe8-445a-862c-5a89a20f6b3c",
        createdDate: "2023-12-29T10:17:53.424Z",
        availability: {
          isHidden: false,
          isAvailableNow: true,
          isUnAvailable: false,
        },
        items: [],
        saveOptionItems: false,
        enableMinimumSelections: false,
        enableMaximumSelections: false,
        someOptionsUnavailable: false,
        optionsCount: 0,
        menusCount: 0,
        optionSetsCount: 0,
        categoriesCount: 0,
        entityType: "MENU_OPTIONS",
        isHidden: false,
      },
    ],
    optionSets: [
      {
        id: "cbddc99b-bb47-4f9a-8959-26da676b74d8",
        createdDate: "2023-12-29T10:17:53.424Z",
        availability: {
          isHidden: false,
          isAvailableNow: true,
          isUnAvailable: false,
        },
        items: [],
        saveOptionItems: false,
        enableMinimumSelections: false,
        enableMaximumSelections: false,
        someOptionsUnavailable: false,
        optionsCount: 0,
        menusCount: 0,
        optionSetsCount: 0,
        categoriesCount: 0,
        entityType: "MENU_OPTIONS",
        isHidden: false,
      },
      {
        id: "5f6a3739-bbe8-445a-862c-5a89a20f6b3c",
        createdDate: "2023-12-29T10:17:53.424Z",
        availability: {
          isHidden: false,
          isAvailableNow: true,
          isUnAvailable: false,
        },
        items: [],
        saveOptionItems: false,
        enableMinimumSelections: false,
        enableMaximumSelections: false,
        someOptionsUnavailable: false,
        optionsCount: 0,
        menusCount: 0,
        optionSetsCount: 0,
        categoriesCount: 0,
        entityType: "MENU_OPTIONS",
        isHidden: false,
      },
    ],
    categories: [
      {
        id: "e612635c-089b-43b4-9c3e-93413dd88c5e",
        createdDate: "2023-12-29T10:17:53.430Z",
        availability: {
          isHidden: false,
          isAvailableNow: true,
          isUnAvailable: false,
        },
        itemsCount: 0,
        optionsCount: 0,
        menusCount: 0,
        optionSetsCount: 0,
        categoriesCount: 0,
        entityType: "MENU_CATEGORY",
        isHidden: false,
      },
      {
        id: "a45c3f7c-fabe-421b-819b-e295d45fd918",
        createdDate: "2023-12-29T10:17:53.431Z",
        availability: {
          isHidden: false,
          isAvailableNow: true,
          isUnAvailable: false,
        },
        itemsCount: 0,
        optionsCount: 0,
        menusCount: 0,
        optionSetsCount: 0,
        categoriesCount: 0,
        entityType: "MENU_CATEGORY",
        isHidden: false,
      },
    ],
    notTaxable: false,
    merchantId: "74d66b02-3739-46d9-896c-8a8bf7474311",
    backgroundPic:
      "https://foodbit-dev-original.s3-us-west-1.amazonaws.com/images/600x/stores/energy-savings-1200x675.jpg",
    profilePic:
      "https://foodbit-dev-original.s3-us-west-1.amazonaws.com/images/300x/stores/energy-savings-1200x675.jpg",
    calories: 777,
    name: {
      en: "Sotosss",
      ar: "AR soto super",
    },
    description: {
      en: "yjjhgjhghjg",
      ar: "hjkhjghjkghjkg",
    },
    total: 143.0,
    price: 143.0,
    textToSpeech: {
      langCode: "IT",
      isEnabled: false,
    },
    foodLabels: ["GLUTEN_FREE"],
    allergies: ["EGG", "PEPPER", "SESAME", "NUT", "GLUTEN"],
    itemsCount: 0,
    optionsCount: 2,
    menusCount: 0,
    optionSetsCount: 2,
    categoriesCount: 2,
    entityType: "MENU_ITEM",
    isHidden: false,
    taxable: true,
  },
  {
    id: "d8191805-b3e3-4163-b1f9-fb3151685c33",
    createdDate: "2023-08-23T09:21:28.823Z",
    lastUpdated: "2023-08-23T10:02:40.566Z",
    availability: {
      isHidden: false,
      isAvailableNow: true,
      isUnAvailable: false,
    },
    categories: [
      {
        id: "d5e17b6f-e0f9-4f40-8bf8-186845ad05e2",
        createdDate: "2023-12-29T10:17:53.431Z",
        availability: {
          isHidden: false,
          isAvailableNow: true,
          isUnAvailable: false,
        },
        itemsCount: 0,
        optionsCount: 0,
        menusCount: 0,
        optionSetsCount: 0,
        categoriesCount: 0,
        entityType: "MENU_CATEGORY",
        isHidden: false,
      },
    ],
    merchantId: "74d66b02-3739-46d9-896c-8a8bf7474311",
    name: {
      en: "coba thai spicy",
    },
    description: {
      en: "",
    },
    total: 25.0,
    price: 25.0,
    itemsCount: 0,
    optionsCount: 0,
    menusCount: 0,
    optionSetsCount: 0,
    categoriesCount: 1,
    entityType: "MENU_ITEM",
    isHidden: false,
  },
  {
    id: "7cf63e96-1782-4d03-83aa-a6fc7e15c29b",
    createdDate: "2023-08-23T09:21:41.286Z",
    lastUpdated: "2023-08-23T10:02:32.814Z",
    availability: {
      isHidden: false,
      isAvailableNow: true,
      isUnAvailable: false,
    },
    categories: [
      {
        id: "d5e17b6f-e0f9-4f40-8bf8-186845ad05e2",
        createdDate: "2023-12-29T10:17:53.431Z",
        availability: {
          isHidden: false,
          isAvailableNow: true,
          isUnAvailable: false,
        },
        itemsCount: 0,
        optionsCount: 0,
        menusCount: 0,
        optionSetsCount: 0,
        categoriesCount: 0,
        entityType: "MENU_CATEGORY",
        isHidden: false,
      },
    ],
    merchantId: "74d66b02-3739-46d9-896c-8a8bf7474311",
    name: {
      en: "spicy thai spring roll",
    },
    description: {
      en: "",
    },
    total: 45.0,
    price: 45.0,
    itemsCount: 0,
    optionsCount: 0,
    menusCount: 0,
    optionSetsCount: 0,
    categoriesCount: 1,
    entityType: "MENU_ITEM",
    isHidden: false,
  },
  {
    id: "be1b2b72-4b3c-4cfa-ac32-0e16faac0e9a",
    createdDate: "2023-01-26T16:41:39.397Z",
    lastUpdated: "2023-03-24T22:09:00.149Z",
    availability: {
      unavailableForStores: [],
      unavailableForStoresIds: [],
      outOfStockForStoreIds: [],
      outOfStockStores: [],
      isHidden: false,
      isAvailableNow: true,
      isUnAvailable: true,
    },
    options: [
      {
        id: "cbddc99b-bb47-4f9a-8959-26da676b74d8",
        createdDate: "2023-12-29T10:17:53.424Z",
        availability: {
          isHidden: false,
          isAvailableNow: true,
          isUnAvailable: false,
        },
        items: [],
        saveOptionItems: false,
        enableMinimumSelections: false,
        enableMaximumSelections: false,
        someOptionsUnavailable: false,
        optionsCount: 0,
        menusCount: 0,
        optionSetsCount: 0,
        categoriesCount: 0,
        entityType: "MENU_OPTIONS",
        isHidden: false,
      },
      {
        id: "88149997-ddd5-4598-83e9-9b4d1116d4ec",
        createdDate: "2023-12-29T10:17:53.424Z",
        availability: {
          isHidden: false,
          isAvailableNow: true,
          isUnAvailable: false,
        },
        items: [],
        saveOptionItems: false,
        enableMinimumSelections: false,
        enableMaximumSelections: false,
        someOptionsUnavailable: false,
        optionsCount: 0,
        menusCount: 0,
        optionSetsCount: 0,
        categoriesCount: 0,
        entityType: "MENU_OPTIONS",
        isHidden: false,
      },
      {
        id: "5f6a3739-bbe8-445a-862c-5a89a20f6b3c",
        createdDate: "2023-12-29T10:17:53.424Z",
        availability: {
          isHidden: false,
          isAvailableNow: true,
          isUnAvailable: false,
        },
        items: [],
        saveOptionItems: false,
        enableMinimumSelections: false,
        enableMaximumSelections: false,
        someOptionsUnavailable: false,
        optionsCount: 0,
        menusCount: 0,
        optionSetsCount: 0,
        categoriesCount: 0,
        entityType: "MENU_OPTIONS",
        isHidden: false,
      },
    ],
    optionSets: [
      {
        id: "cbddc99b-bb47-4f9a-8959-26da676b74d8",
        createdDate: "2023-12-29T10:17:53.424Z",
        availability: {
          isHidden: false,
          isAvailableNow: true,
          isUnAvailable: false,
        },
        items: [],
        saveOptionItems: false,
        enableMinimumSelections: false,
        enableMaximumSelections: false,
        someOptionsUnavailable: false,
        optionsCount: 0,
        menusCount: 0,
        optionSetsCount: 0,
        categoriesCount: 0,
        entityType: "MENU_OPTIONS",
        isHidden: false,
      },
      {
        id: "88149997-ddd5-4598-83e9-9b4d1116d4ec",
        createdDate: "2023-12-29T10:17:53.424Z",
        availability: {
          isHidden: false,
          isAvailableNow: true,
          isUnAvailable: false,
        },
        items: [],
        saveOptionItems: false,
        enableMinimumSelections: false,
        enableMaximumSelections: false,
        someOptionsUnavailable: false,
        optionsCount: 0,
        menusCount: 0,
        optionSetsCount: 0,
        categoriesCount: 0,
        entityType: "MENU_OPTIONS",
        isHidden: false,
      },
      {
        id: "5f6a3739-bbe8-445a-862c-5a89a20f6b3c",
        createdDate: "2023-12-29T10:17:53.424Z",
        availability: {
          isHidden: false,
          isAvailableNow: true,
          isUnAvailable: false,
        },
        items: [],
        saveOptionItems: false,
        enableMinimumSelections: false,
        enableMaximumSelections: false,
        someOptionsUnavailable: false,
        optionsCount: 0,
        menusCount: 0,
        optionSetsCount: 0,
        categoriesCount: 0,
        entityType: "MENU_OPTIONS",
        isHidden: false,
      },
    ],
    categories: [
      {
        id: "e612635c-089b-43b4-9c3e-93413dd88c5e",
        createdDate: "2023-12-29T10:17:53.431Z",
        availability: {
          isHidden: false,
          isAvailableNow: true,
          isUnAvailable: false,
        },
        itemsCount: 0,
        optionsCount: 0,
        menusCount: 0,
        optionSetsCount: 0,
        categoriesCount: 0,
        entityType: "MENU_CATEGORY",
        isHidden: false,
      },
    ],
    notTaxable: false,
    merchantId: "74d66b02-3739-46d9-896c-8a8bf7474311",
    backgroundPic:
      "https://foodbit-dev-original.s3-us-west-1.amazonaws.com/images/600x/stores/CHW.jpg",
    profilePic:
      "https://foodbit-dev-original.s3-us-west-1.amazonaws.com/images/300x/stores/CHW.jpg",
    calories: 444,
    name: {
      en: "Bakso",
      ar: "AR bakso",
    },
    description: {
      en: "BaksoBaksoB aksoBakso Bak  oBaksoB akso",
    },
    total: 211.0,
    price: 211.0,
    itemsCount: 0,
    optionsCount: 3,
    menusCount: 0,
    optionSetsCount: 3,
    categoriesCount: 1,
    entityType: "MENU_ITEM",
    isHidden: false,
    taxable: true,
  },
];
